export const dashboardEvents = [
  {
    id: "coaching-camille",
    type: "coaching",
    dayOffset: 0,
    startTime: "08:30",
    duration: 60,
    client: "Camille Martin",
    location: "Studio principal",
  },
  {
    id: "class-hiit",
    type: "group-class",
    dayOffset: 0,
    startTime: "12:15",
    duration: 45,
    className: "HIIT Express",
    location: "Salle Horizon",
  },
  {
    id: "coaching-lea",
    type: "coaching",
    dayOffset: 0,
    startTime: "17:30",
    duration: 60,
    client: "Léa Bernard",
    location: "Studio principal",
  },
  {
    id: "class-mobility",
    type: "group-class",
    dayOffset: -2,
    startTime: "18:00",
    duration: 60,
    className: "Mobilité",
    location: "Salle Horizon",
  },
  {
    id: "coaching-thomas",
    type: "coaching",
    dayOffset: -1,
    startTime: "10:00",
    duration: 75,
    client: "Thomas Petit",
    location: "Studio principal",
  },
  {
    id: "class-cross-training",
    type: "group-class",
    dayOffset: 1,
    startTime: "18:30",
    duration: 60,
    className: "Cross Training",
    location: "Gymnase Nord",
  },
  {
    id: "coaching-ines",
    type: "coaching",
    dayOffset: 2,
    startTime: "09:00",
    duration: 60,
    client: "Inès Robert",
    location: "Studio principal",
  },
  {
    id: "class-tabata",
    type: "group-class",
    dayOffset: 3,
    startTime: "12:30",
    duration: 45,
    className: "Tabata",
    location: "Salle Horizon",
  },
  {
    id: "coaching-julien",
    type: "coaching",
    dayOffset: 4,
    startTime: "11:00",
    duration: 90,
    client: "Julien Richard",
    location: "Parc Central",
  },
];

export const dashboardFilters = [
  { value: "all", label: "Tous" },
  { value: "coaching", label: "Coachings" },
  { value: "group-class", label: "Cours collectifs" },
];
