export const dashboardEvents = [
  {
    id: "coaching-camille",
    type: "coaching",
    dayOffset: 0,
    startTime: "08:30",
    duration: 60,
    location: "Studio principal",
    description: "Séance de renforcement général adaptée aux objectifs de Camille.",
    client: "Camille Martin",
  },
  {
    id: "class-hiit",
    type: "group-class",
    dayOffset: 0,
    startTime: "12:15",
    duration: 45,
    location: "Salle Horizon",
    description: "Circuit court alternant des phases de travail intense et de récupération.",
    className: "HIIT Express",
  },
  {
    id: "coaching-lea",
    type: "coaching",
    dayOffset: 0,
    startTime: "17:30",
    duration: 60,
    location: "Studio principal",
    description: "Travail de mobilité et de renforcement du bas du corps.",
    client: "Léa Bernard",
  },
  {
    id: "class-mobility",
    type: "group-class",
    dayOffset: -2,
    startTime: "18:00",
    duration: 60,
    location: "Salle Horizon",
    description: "Cours axé sur la mobilité articulaire et les amplitudes de mouvement.",
    className: "Mobilité",
  },
  {
    id: "coaching-thomas",
    type: "coaching",
    dayOffset: -1,
    startTime: "10:00",
    duration: 75,
    location: "Studio principal",
    description: "Séance complète consacrée à la technique et au renforcement.",
    client: "Thomas Petit",
  },
  {
    id: "class-cross-training",
    type: "group-class",
    dayOffset: 1,
    startTime: "18:30",
    duration: 60,
    location: "Gymnase Nord",
    description: "Enchaînement cardio et renforcement sous forme de plusieurs ateliers.",
    className: "Cross Training",
  },
  {
    id: "coaching-ines",
    type: "coaching",
    dayOffset: 2,
    startTime: "09:00",
    duration: 60,
    location: "Studio principal",
    description: "Coaching orienté sur le gainage et la stabilité.",
    client: "Inès Robert",
  },
  {
    id: "class-tabata",
    type: "group-class",
    dayOffset: 3,
    startTime: "12:30",
    duration: 45,
    location: "Salle Horizon",
    description: "Séquences de travail courtes organisées au format Tabata.",
    className: "Tabata",
  },
  {
    id: "coaching-julien",
    type: "coaching",
    dayOffset: 4,
    startTime: "11:00",
    duration: 90,
    location: "Parc Central",
    description: "Séance en extérieur combinant course, mobilité et renforcement.",
    client: "Julien Richard",
  },
];

export const dashboardFilters = [
  { value: "all", label: "Tous" },
  { value: "coaching", label: "Coachings" },
  { value: "group-class", label: "Cours collectifs" },
];
